/**
 * Converts report markdown (### headings, **bold**, * lists) to HTML for display and download.
 */
export function markdownReportToHtml(markdown: string): string {
  const lines = markdown.split(/\r?\n/);
  const out: string[] = [];
  let inList = false;

  function flushList() {
    if (inList) {
      out.push("</ul>");
      inList = false;
    }
  }

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();

    if (trimmed.startsWith("### ")) {
      flushList();
      const title = applyBoldToHtml(trimmed.slice(4).trim());
      out.push(`<h3 class="report-title">${title}</h3>`);
      continue;
    }

    if (trimmed.startsWith("**") && (trimmed.endsWith(":**") || trimmed.includes(":**"))) {
      flushList();
      const content = applyBoldToHtml(trimmed);
      out.push(`<p class="report-label-line">${content}</p>`);
      continue;
    }

    if (trimmed.startsWith("* ") || trimmed.startsWith("- ")) {
      if (!inList) {
        out.push('<ul class="report-list">');
        inList = true;
      }
      const content = applyBoldToHtml(trimmed.slice(2).trim());
      out.push(`<li>${content}</li>`);
      continue;
    }

    if (trimmed === "") {
      flushList();
      out.push('<div class="report-spacer"></div>');
      continue;
    }

    flushList();
    const content = applyBoldToHtml(trimmed);
    out.push(`<p class="report-para">${content}</p>`);
  }

  flushList();
  return out.join("\n");
}

/** Converts **bold** to <strong> and escapes HTML */
function applyBoldToHtml(text: string): string {
  const parts = text.split(/(\*\*[^*]+\*\*)/g);
  return parts
    .map((p) => {
      if (p.startsWith("**") && p.endsWith("**"))
        return "<strong>" + escapeHtml(p.slice(2, -2)) + "</strong>";
      return escapeHtml(p);
    })
    .join("");
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Full HTML document for download/print with embedded styles */
export function wrapReportAsDocument(htmlContent: string, title: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(title)}</title>
  <style>
    * { box-sizing: border-box; }
    body {
      font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif;
      line-height: 1.6;
      color: #1e293b;
      background: #fff;
      max-width: 720px;
      margin: 0 auto;
      padding: 2rem 1.5rem;
    }
    .report-title {
      font-size: 1.25rem;
      font-weight: 700;
      color: #0f172a;
      margin: 1.5rem 0 0.75rem;
      padding-bottom: 0.35rem;
      border-bottom: 2px solid #e2e8f0;
    }
    .report-title:first-child { margin-top: 0; }
    .report-label-line, .report-para {
      margin: 0.4rem 0;
      font-size: 0.95rem;
    }
    .report-list {
      margin: 0.5rem 0 1rem 1.25rem;
      padding-left: 1.25rem;
    }
    .report-list li { margin: 0.25rem 0; }
    .report-spacer { height: 0.75rem; }
    strong { font-weight: 600; color: #0f172a; }
    .doc-header {
      text-align: center;
      margin-bottom: 2rem;
      padding-bottom: 1.5rem;
      border-bottom: 2px solid #e2e8f0;
    }
    .doc-header h1 { font-size: 1.5rem; margin: 0; color: #0f172a; }
    .doc-header p { margin: 0.25rem 0 0; font-size: 0.875rem; color: #64748b; }
    @media print {
      body { padding: 1rem; }
      .report-title { break-after: avoid; }
    }
  </style>
</head>
<body>
  <div class="doc-header">
    <h1>${escapeHtml(title)}</h1>
    <p>Generated by SafeMOM · ${new Date().toLocaleDateString(undefined, { dateStyle: "long" })}</p>
  </div>
  <div class="report-body">
    ${htmlContent}
  </div>
  <p style="margin-top: 2rem; font-size: 0.8rem; color: #64748b;">
    This report is AI-generated and does not replace professional medical advice. Always consult your healthcare provider.
  </p>
</body>
</html>`;
}
